In [1]:
import numpy as np
import gym
import time
import random
from IPython.display import clear_output

In [2]:
environment = gym.make("FrozenLake-v1")

In [3]:
actionSpaceSize = environment.action_space.n
stateSpaceSize = environment.observation_space.n

qTable = np.zeros((stateSpaceSize, actionSpaceSize))
print("******Q-Table 1******", "\n\n", qTable)

******Q-Table 1****** 

 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
numEpisodes = 9000
maxStepsPerEpisode = 100

learningRate = 0.1
discountRate = 0.9

explorationRate = 1
maxExplorationRate = 1
minExplorationRate = 0.01
explorationDecay = 0.001

In [5]:
rewardsAllEpisodes = []

for episode in range(numEpisodes):
    state = environment.reset()
    
    done = False
    rewardsCurrentEpisode = 0
    
    for step in range(maxStepsPerEpisode):
        explorationRateThreshold = random.uniform(0,1)
        if explorationRateThreshold > explorationRate:
            action = np.argmax(qTable[state,:])
        else:
            action = environment.action_space.sample()
            
        newState, reward,  done, info = environment.step(action)
        
        # Update Q-table for Q(s,a)
        qTable[state, action] = qTable[state, action] * (1 - learningRate) + learningRate * (reward + discountRate * np.max(qTable[newState, :]))
    
        state = newState
        rewardsCurrentEpisode += reward
        
        if done == True:
            break
            
    explorationRate = minExplorationRate + (maxExplorationRate - minExplorationRate) * np.exp(-explorationDecay*episode)
    rewardsAllEpisodes.append(rewardsCurrentEpisode)
    
rewardsPerThousandCounts = np.split(np.array(rewardsAllEpisodes),numEpisodes/1000)
count = 1000
print("******Average Reward Per 1000 Episodes******\n")
for r in rewardsPerThousandCounts:
    print(count, ": ", str(sum(r/1000)))
    count += 1000
    
print("\n\n******Q-Table 2******\n")
print(qTable)

******Average Reward Per 1000 Episodes******

1000 :  0.04200000000000003
2000 :  0.16200000000000012
3000 :  0.2940000000000002
4000 :  0.4080000000000003
5000 :  0.4880000000000004
6000 :  0.4210000000000003
7000 :  0.5480000000000004
8000 :  0.4880000000000004
9000 :  0.5820000000000004


******Q-Table 2******

[[0.05119954 0.06090029 0.05084118 0.05018583]
 [0.02776524 0.02495063 0.02847737 0.06282199]
 [0.08781348 0.03873646 0.03887193 0.03905012]
 [0.03140255 0.02912191 0.03177502 0.03729913]
 [0.09331375 0.06512045 0.06015906 0.04289752]
 [0.         0.         0.         0.        ]
 [0.12230854 0.02765741 0.03292698 0.03376986]
 [0.         0.         0.         0.        ]
 [0.06781841 0.07054627 0.07642782 0.18109315]
 [0.11205108 0.2829448  0.13755302 0.12212449]
 [0.36177856 0.21073659 0.12097812 0.12059501]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.14325398 0.21195859 0.46438756 0.2128218 ]
 [0.35133014 0.81121226 0.

In [6]:
for episode in range(5):
    state = environment.reset()
    done = False
    print("*****EPISODE", episode+1, "*****\n\n\n\n")
    time.sleep(1)
    
    for step in range(maxStepsPerEpisode):
        clear_output(wait=True)
        environment.render()
        time.sleep(0.3)
        
        action = np.argmax(qTable[state, :])
        newState, reward, done, info = environment.step(action)
        
        if done:
            clear_output(wait=True)
            environment.render()
            if reward == 1:
                print("*****YOU REACHED THE GOAL*****")
                time.sleep(3)
            else:
                print("*****YOU FELL INTO THE HOLE*****")
                time.sleep(3)
            clear_output(wait=True)
            break
            
        state = newState
        
environment.close()
        

  (Left)
SFFF
FHFH
FFFH
HFFG
*****YOU FELL INTO THE HOLE*****
